export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  UNAUTHENTICATED: "UNAUTHENTICATED",
} as const;

export const SUBSCRIPTION_BLOCKED_CODE = "SUBSCRIPTION_BLOCKED" as const;

export const PERMISSION_DENIED_CODE = "PERMISSION_DENIED" as const;

export const VALIDATION_ERROR_CODE = "VALIDATION_ERROR" as const;
