"""add_commission_rate_to_contract

Revision ID: 31280152caec
Revises: 0c1727d8b1e4
Create Date: 2026-02-18 02:42:47.499968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31280152caec'
down_revision: Union[str, Sequence[str], None] = '0c1727d8b1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('commission_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'commission_rate')
    # ### end Alembic commands ###
