"""Add commission_pay to payroll

Revision ID: 38b4ec6ebf8a
Revises: 91c399ae6832
Create Date: 2026-02-19 02:39:58.402076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b4ec6ebf8a'
down_revision: Union[str, Sequence[str], None] = '91c399ae6832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('commission_pay', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'commission_pay')
    # ### end Alembic commands ###
