"""add_gym_subscription_expiry

Revision ID: 3d0c7f9e7eb7
Revises: d9e8c7b6a5f4
Create Date: 2026-04-21 03:47:55.571424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0c7f9e7eb7'
down_revision: Union[str, Sequence[str], None] = 'd9e8c7b6a5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_index(op.f('ix_access_logs_status_scan_time_user_id'), table_name='access_logs')
    op.drop_constraint(op.f('uq_chat_read_receipts_thread_user'), 'chat_read_receipts', type_='unique')
    op.create_unique_constraint('uq_chat_read_receipts_gym_thread_user', 'chat_read_receipts', ['gym_id', 'thread_id', 'user_id'])
    op.drop_constraint(op.f('uq_chat_threads_customer_coach'), 'chat_threads', type_='unique')
    op.create_unique_constraint('uq_chat_threads_gym_customer_coach', 'chat_threads', ['gym_id', 'customer_id', 'coach_id'])
    op.drop_constraint(op.f('uq_class_reservation_session_member'), 'class_reservations', type_='unique')
    op.create_unique_constraint('uq_class_reservation_gym_session_member', 'class_reservations', ['gym_id', 'session_id', 'member_id'])
    op.drop_constraint(op.f('class_reservations_session_id_fkey'), 'class_reservations', type_='foreignkey')
    op.create_foreign_key(None, 'class_reservations', 'class_sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('class_sessions_template_id_fkey'), 'class_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'class_sessions', 'class_templates', ['template_id'], ['id'])
    op.drop_index(op.f('ix_coach_exercise_templates_coach_id'), table_name='coach_exercise_templates')
    op.drop_index(op.f('ix_diet_library_items_name'), table_name='diet_library_items')
    op.drop_index(op.f('ix_diet_library_items_owner_coach_id'), table_name='diet_library_items')
    op.drop_index(op.f('ix_diet_plans_creator_status'), table_name='diet_plans')
    op.drop_index(op.f('ix_diet_plans_member_status'), table_name='diet_plans')
    op.drop_index(op.f('ix_diet_plans_parent_plan_id'), table_name='diet_plans')
    op.drop_index(op.f('ix_exercise_library_items_name'), table_name='exercise_library_items')
    op.drop_index(op.f('ix_exercise_library_items_owner_coach_id'), table_name='exercise_library_items')
    op.drop_index(op.f('ix_exercise_library_recent_coach_id'), table_name='exercise_library_recent')
    op.drop_index(op.f('ix_exercise_library_recent_last_used_at'), table_name='exercise_library_recent')
    op.add_column('gyms', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gyms', sa.Column('grace_period_days', sa.Integer(), nullable=False, server_default='7'))
    op.drop_constraint(op.f('uq_member_diet_tracking_day'), 'member_diet_tracking_days', type_='unique')
    op.create_unique_constraint('uq_member_diet_tracking_gym_day', 'member_diet_tracking_days', ['gym_id', 'member_id', 'diet_plan_id', 'tracked_for'])
    op.create_index(op.f('ix_payroll_settings_gym_id'), 'payroll_settings', ['gym_id'], unique=False)
    op.drop_constraint(op.f('products_sku_key'), 'products', type_='unique')
    op.create_unique_constraint('uq_products_gym_branch_sku', 'products', ['gym_id', 'branch_id', 'sku'])
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'FRONT_DESK', 'RECEPTION', 'COACH', 'EMPLOYEE', 'CASHIER', 'CUSTOMER', name='role', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email_gym'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email_gym'), 'users', ['email', 'gym_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'FRONT_DESK', 'RECEPTION', 'COACH', 'EMPLOYEE', 'CASHIER', 'CUSTOMER', name='role', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint('uq_products_gym_branch_sku', 'products', type_='unique')
    op.create_unique_constraint(op.f('products_sku_key'), 'products', ['sku'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payroll_settings_gym_id'), table_name='payroll_settings')
    op.drop_constraint('uq_member_diet_tracking_gym_day', 'member_diet_tracking_days', type_='unique')
    op.create_unique_constraint(op.f('uq_member_diet_tracking_day'), 'member_diet_tracking_days', ['member_id', 'diet_plan_id', 'tracked_for'], postgresql_nulls_not_distinct=False)
    op.drop_column('gyms', 'grace_period_days')
    op.drop_column('gyms', 'subscription_expires_at')
    op.create_index(op.f('ix_exercise_library_recent_last_used_at'), 'exercise_library_recent', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_exercise_library_recent_coach_id'), 'exercise_library_recent', ['coach_id'], unique=False)
    op.create_index(op.f('ix_exercise_library_items_owner_coach_id'), 'exercise_library_items', ['owner_coach_id'], unique=False)
    op.create_index(op.f('ix_exercise_library_items_name'), 'exercise_library_items', ['name'], unique=False)
    op.create_index(op.f('ix_diet_plans_parent_plan_id'), 'diet_plans', ['parent_plan_id'], unique=False)
    op.create_index(op.f('ix_diet_plans_member_status'), 'diet_plans', ['member_id', 'status'], unique=False)
    op.create_index(op.f('ix_diet_plans_creator_status'), 'diet_plans', ['creator_id', 'status'], unique=False)
    op.create_index(op.f('ix_diet_library_items_owner_coach_id'), 'diet_library_items', ['owner_coach_id'], unique=False)
    op.create_index(op.f('ix_diet_library_items_name'), 'diet_library_items', ['name'], unique=False)
    op.create_index(op.f('ix_coach_exercise_templates_coach_id'), 'coach_exercise_templates', ['coach_id'], unique=False)
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('class_sessions_template_id_fkey'), 'class_sessions', 'class_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'class_reservations', type_='foreignkey')
    op.create_foreign_key(op.f('class_reservations_session_id_fkey'), 'class_reservations', 'class_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_class_reservation_gym_session_member', 'class_reservations', type_='unique')
    op.create_unique_constraint(op.f('uq_class_reservation_session_member'), 'class_reservations', ['session_id', 'member_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_chat_threads_gym_customer_coach', 'chat_threads', type_='unique')
    op.create_unique_constraint(op.f('uq_chat_threads_customer_coach'), 'chat_threads', ['customer_id', 'coach_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_chat_read_receipts_gym_thread_user', 'chat_read_receipts', type_='unique')
    op.create_unique_constraint(op.f('uq_chat_read_receipts_thread_user'), 'chat_read_receipts', ['thread_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_access_logs_status_scan_time_user_id'), 'access_logs', ['status', 'scan_time', 'user_id'], unique=False)
    op.drop_table('system_config')
    # ### end Alembic commands ###
