"""Add profile fields

Revision ID: 467f6e6c63b7
Revises: fe27ab52359a
Create Date: 2026-02-20 08:23:36.601604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467f6e6c63b7'
down_revision: Union[str, Sequence[str], None] = 'fe27ab52359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'profile_picture_url')
    # ### end Alembic commands ###
