"""Add support tickets and messages

Revision ID: 699939ca0cfb
Revises: f7a1c9d3b2e4
Create Date: 2026-02-23 19:24:41.986362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699939ca0cfb'
down_revision: Union[str, Sequence[str], None] = 'f7a1c9d3b2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_feedback_created_at'), 'gym_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_gym_feedback_member_id'), 'gym_feedback', ['member_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'TECHNICAL', 'BILLING', 'SUBSCRIPTION', name='ticketcategory'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_customer_id'), 'support_tickets', ['customer_id'], unique=False)
    op.create_table('whatsapp_automation_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('trigger_name', sa.String(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', name='uq_whatsapp_automation_rules_event_type')
    )
    op.create_index(op.f('ix_whatsapp_automation_rules_event_type'), 'whatsapp_automation_rules', ['event_type'], unique=False)
    op.create_table('whatsapp_delivery_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_ref', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_whatsapp_delivery_logs_idempotency_key')
    )
    op.create_index(op.f('ix_whatsapp_delivery_logs_event_type'), 'whatsapp_delivery_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_delivery_logs_status'), 'whatsapp_delivery_logs', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_delivery_logs_user_id'), 'whatsapp_delivery_logs', ['user_id'], unique=False)
    op.create_table('diet_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('diet_plan_id', sa.Uuid(), nullable=False),
    sa.Column('coach_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['diet_plan_id'], ['diet_plans.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_feedback_coach_id'), 'diet_feedback', ['coach_id'], unique=False)
    op.create_index(op.f('ix_diet_feedback_created_at'), 'diet_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_diet_feedback_diet_plan_id'), 'diet_feedback', ['diet_plan_id'], unique=False)
    op.create_index(op.f('ix_diet_feedback_member_id'), 'diet_feedback', ['member_id'], unique=False)
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_messages_ticket_id'), 'support_messages', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_messages_ticket_id'), table_name='support_messages')
    op.drop_table('support_messages')
    op.drop_index(op.f('ix_diet_feedback_member_id'), table_name='diet_feedback')
    op.drop_index(op.f('ix_diet_feedback_diet_plan_id'), table_name='diet_feedback')
    op.drop_index(op.f('ix_diet_feedback_created_at'), table_name='diet_feedback')
    op.drop_index(op.f('ix_diet_feedback_coach_id'), table_name='diet_feedback')
    op.drop_table('diet_feedback')
    op.drop_index(op.f('ix_whatsapp_delivery_logs_user_id'), table_name='whatsapp_delivery_logs')
    op.drop_index(op.f('ix_whatsapp_delivery_logs_status'), table_name='whatsapp_delivery_logs')
    op.drop_index(op.f('ix_whatsapp_delivery_logs_event_type'), table_name='whatsapp_delivery_logs')
    op.drop_table('whatsapp_delivery_logs')
    op.drop_index(op.f('ix_whatsapp_automation_rules_event_type'), table_name='whatsapp_automation_rules')
    op.drop_table('whatsapp_automation_rules')
    op.drop_index(op.f('ix_support_tickets_customer_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_gym_feedback_member_id'), table_name='gym_feedback')
    op.drop_index(op.f('ix_gym_feedback_created_at'), table_name='gym_feedback')
    op.drop_table('gym_feedback')
    # ### end Alembic commands ###
