"""Add branch_id to audit and support models

Revision ID: fb95e975094d
Revises: c4b2a1f9e8d7
Create Date: 2026-04-21 19:04:40.222204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb95e975094d'
down_revision: Union[str, Sequence[str], None] = 'c4b2a1f9e8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('branch_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_logs_branch_id'), 'audit_logs', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'branches', ['branch_id'], ['id'])
    op.add_column('support_tickets', sa.Column('branch_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_support_tickets_branch_id'), 'support_tickets', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'support_tickets', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_support_tickets_branch_id'), table_name='support_tickets')
    op.drop_column('support_tickets', 'branch_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_branch_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'branch_id')
    # ### end Alembic commands ###
