import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from "react";
import * as SecureStore from "expo-secure-store";

import { fonts, themes, type Locale, type ThemeMode } from "@/lib/theme";

type ThemeTokens = (typeof themes)[keyof typeof themes];
type CopySet = (typeof copy)[keyof typeof copy];

const THEME_STORAGE_KEY = "gym-erp.mobile.theme";
const LOCALE_STORAGE_KEY = "gym-erp.mobile.locale";

const copy = {
  en: {
    appName: "Gym ERP",
    controls: {
      theme: "Theme",
      language: "Language",
    },
    tabs: {
      home: "Home",
      qr: "Scan",
      plans: "Plans",
      progress: "Progress",
      more: "More",
    },
    common: {
      billing: "Billing",
      notifications: "Notifications",
      support: "Support",
      chat: "Chat",
      lostFound: "Lost & Found",
      profile: "Profile",
      feedbackHistory: "Feedback History",
      signOut: "Sign out",
      noData: "No data yet.",
      loading: "Loading...",
      noActivePlan: "No active plan",
      noCurrentPlan: "No current plan",
      noComment: "No comment",
      noMessagesYet: "No messages yet.",
      noLocationAdded: "No location added",
      customer: "Customer",
      coach: "Coach",
      on: "On",
      off: "Off",
      yes: "Yes",
      no: "No",
      minutesShort: "min",
      days: "days",
      expectedSessions30d: "expected sessions / 30d",
      unread: "Unread",
      save: "Save",
      cancel: "Cancel",
      send: "Send",
      create: "Create",
      update: "Update",
      submit: "Submit",
      reply: "Reply",
      note: "Note",
      message: "Message",
      status: "Status",
      category: "Category",
      loadingDetails: "Loading details...",
      successUpdated: "Updated successfully",
      errorTryAgain: "Something went wrong. Please try again.",
      attachFile: "Attach file",
      attachPhoto: "Attach photo",
      attachment: "Attachment",
      uploading: "Uploading...",
      photoPermissionDenied: "Photo library access is blocked. Enable it from app settings.",
    },
    login: {
      title: "Gym ERP",
      subtitle: "Customer mobile access for QR entry, plans, progress, and support.",
      kicker: "Phase 2 customer app",
      signIn: "Sign in",
      signInButton: "Continue",
      signingIn: "Signing in...",
      email: "Email",
      password: "Password",
      localDemo: "Local demo accounts",
      localDemoHint: "Use the seeded customer account for a full Phase 2 walkthrough.",
    },
    home: {
      greeting: "Hi",
      subtitle: "Customer control center",
      billingBadge: "Billing",
      subscription: "Subscription",
      plan: "Plan",
      status: "Status",
      renew: "Renew from billing",
      workoutPlans: "Workout plans",
      dietPlans: "Diet plans",
      checkIns: "Check-ins",
      unreadChat: "Unread chat",
      latestBiometric: "Latest biometric",
      weight: "Weight",
      bodyFat: "Body fat",
      noBiometrics: "No biometric logs yet.",
      recentReceipts: "Recent receipts",
      noReceipts: "No receipts yet.",
      quickActions: "Quick actions",
      logBodyMetrics: "Log body metrics",
      requestSupport: "Request support",
      reportLostItem: "Report lost item",
      leaveFeedback: "Leave feedback",
      achievements: "Achievements",
      achievementsSubtitle: "Your gym milestones, streaks, and unlocked badges.",
      currentStreak: "Current streak",
      bestStreak: "Best streak",
      totalVisits: "Total visits",
      unlocked: "unlocked",
      noBadges: "No badges unlocked yet.",
      locked: "Locked",
      viewAllBadges: "View all badges",
      earnedOn: "Earned",
    },
    qr: {
      title: "Check-in Scan",
      subtitle: "Scan the gym QR shown at reception, the gate, or the check-in point.",
      entranceStatus: "Entrance status",
      cameraReady: "Camera is ready",
      cameraHint: "Point your phone at the gym QR to scan it.",
      noPersonalCode: "Customers do not carry their own QR code in the app.",
      grantCamera: "Allow camera",
      cameraDenied: "Camera access is blocked. Enable it from app settings.",
      scanAgain: "Scan again",
      lastScan: "Last scan",
      scannerFrame: "Align the gym QR inside the frame",
      scanResult: "Check-in result",
      scanStatus: "Scan status",
      scanReason: "Reason",
      scanKiosk: "Kiosk",
      scanTime: "Time",
      invalidCode: "This QR code is not a valid gym kiosk code.",
      scanning: "Checking access...",
      noReason: "No additional reason",
    },
    plans: {
      title: "Plans",
      subtitle: "Your assigned workout and diet plans.",
      workoutPlans: "Workout plans",
      dietPlans: "Diet plans",
      noWorkoutPlans: "No workout plans assigned.",
      noDietPlans: "No diet plans assigned.",
      startSession: "Start session",
      resumeSession: "Resume session",
      abandonSession: "Abandon session",
      completeExercise: "Complete exercise",
      skipExercise: "Skip exercise",
      finishSession: "Finish session",
      currentExercise: "Current exercise",
      progress: "Progress",
      target: "Target",
      section: "Section",
      chooseSection: "Choose section",
      setsCompleted: "Sets completed",
      repsCompleted: "Reps completed",
      weightKg: "Weight (kg)",
      exerciseNotes: "Exercise notes",
      sessionNotes: "Session notes",
      sessionDuration: "Session duration (min)",
      prToggle: "This was a PR",
      prType: "PR type",
      prValue: "PR value",
      prNotes: "PR notes",
      recentSessions: "Recent sessions",
      noSessionHistory: "No completed sessions yet.",
      dietTracker: "Diet tracker",
      dayAdherence: "Daily adherence",
      dayNotes: "Day notes",
      saveDay: "Save day",
      noStructuredDiet: "This diet does not have structured days and meals yet.",
      planContent: "Plan content",
      markDone: "Mark done",
      done: "Done",
      workoutStarted: "Workout session started.",
      workoutSaved: "Exercise logged.",
      workoutSkipped: "Exercise skipped.",
      workoutFinished: "Workout session finished.",
      workoutAbandoned: "Active workout session discarded.",
      dietSaved: "Diet day updated.",
    },
    progress: {
      title: "Progress",
      subtitle: "Biometrics, attendance history, and workout sessions.",
      biometrics: "Biometrics",
      noBiometrics: "No biometric history yet.",
      recentSessions: "Recent sessions",
      noSessions: "No session logs yet.",
      attendance: "Attendance",
      recentScans: "recent access scans",
      thisMonth: "This month",
      lastWeight: "Last weight",
      lastBodyFat: "Last body fat",
      bodyFat: "body fat",
      muscleMass: "muscle",
      workouts30d: "Workouts / 30d",
      attendanceTimeline: "Recent check-ins",
      workoutTrend: "Workout trend",
      bodyMetricsTrend: "Body metrics trend",
      weightTrend: "Weight trend",
      bodyFatTrend: "Body fat trend",
      muscleTrend: "Muscle trend",
      attendanceStats: "Attendance milestones",
      prSection: "Exercise PRs",
      noPersonalRecords: "No PRs logged yet. Mark a PR during a workout session and it will appear here.",
      prFallback: "Exercise PR",
      latest: "Latest",
      range: "Range",
      change: "Change",
      logBodyMetrics: "Log body metrics",
      saveBodyMetrics: "Save body metrics",
      savingBodyMetrics: "Saving metrics...",
      heightCm: "Height (cm)",
      weightKg: "Weight (kg)",
      bodyFatPct: "Body fat (%)",
      muscleMassKg: "Muscle mass (kg)",
      metricsSaved: "Body metrics saved.",
      graphNoData: "Add body metrics to see graphs here.",
      latestSessionNotes: "Latest session notes",
      noTrend: "No workout trend yet.",
      noAttendance: "No check-ins yet.",
      noSessionNotes: "No session notes yet.",
    },
    more: {
      title: "More",
      subtitle: "Customer services, profile, and app settings.",
      customerAccount: "Customer account",
      billing: "Billing and renewal requests",
      notifications: "Notifications",
      support: "Support tickets",
      chat: "Chat threads",
      lostFound: "Lost & Found",
      profile: "Profile and settings",
      feedback: "Feedback history",
    },
    billingScreen: {
      subtitle: "Renewal requests, offers, receipts, and payment policy.",
      renewalRequests: "Renewal requests",
      noRenewalRequests: "No renewal requests yet.",
      renewalOffers: "Renewal offers",
      receipts: "Receipts",
      paymentPolicy: "Payment policy",
      currentPlan: "Current plan",
      expiryDate: "Expiry date",
      subscriptionRequests: "Subscription requests",
      requestRenewal: "Request renewal",
      requestFreeze: "Request freeze",
      requestUnfreeze: "Request unfreeze",
      contactSupport: "Contact support",
      requestExtension: "Request extension",
      requestActivationExtend: "Request activation / extend",
      noExpirySet: "No expiry date set",
      activeTitle: "Subscription active",
      activeDesc: "Your plan is active. You can request an extension or freeze from this page.",
      frozenTitle: "Subscription frozen",
      frozenDesc: "Your subscription is frozen. Request unfreeze to restore full access.",
      expiredTitle: "Subscription expired",
      expiredDesc: "Your subscription has expired. Request renewal or extension to continue.",
      noneTitle: "No active subscription",
      noneDesc: "No active subscription is linked to your account. Request activation or extension.",
      requestTitle: "Submit renewal request",
      requestHelp: "Send your renewal request here, then pay at the gym in cash and wait for staff approval.",
      selectedOffer: "Selected offer",
      customerNote: "Customer note",
      customerNotePlaceholder: "Tell the gym when you plan to pay or leave any helpful note.",
      submitRequest: "Submit renewal request",
      submittingRequest: "Submitting request...",
    },
    notificationsScreen: {
      subtitle: "Recent customer events and inbox items.",
    },
    supportScreen: {
      subtitle: "Open customer support tickets and recent replies.",
      noTickets: "No support tickets yet.",
      newTicket: "Create support ticket",
      subject: "Subject",
      subjectPlaceholder: "Short title for your issue",
      messagePlaceholder: "Explain what you need help with",
      sendReply: "Send reply",
      sendingReply: "Sending reply...",
      creatingTicket: "Creating ticket...",
      pickTicket: "Pick a ticket to continue the conversation.",
    },
    chatScreen: {
      subtitle: "Coach conversations and unread thread counts.",
      subtitleStart: "Pick a coach, start a thread, and keep replies in one place.",
      noThreads: "No chat threads yet.",
      startThread: "Start chat",
      newConversation: "New conversation",
      startConversation: "Start conversation",
      selectedCoachLabel: "Selected coach:",
      coachId: "Coach",
      coachIdPlaceholder: "Choose a coach",
      openThread: "Open thread",
      threadMessages: "Thread messages",
      threadHint: "Phone-style conversation view",
      emptyState: "Pick a thread or start a new conversation.",
      messagePlaceholder: "Write a message",
      markRead: "Mark as read",
      creatingThread: "Starting chat...",
      sendingMessage: "Sending message...",
      pickThread: "Pick a thread to see the full conversation.",
      noCoaches: "No coaches available yet.",
      threadStarted: "Chat is ready.",
      unreadActive: "Unread",
      liveNow: "Live",
      recording: "Recording voice note...",
      voicePreview: "Voice note preview",
      acceptSend: "Accept & Send",
      discard: "Discard",
      microphoneUnavailable: "Unable to access microphone.",
      voiceUnavailable: "Voice notes need a newer Expo Go or a development build.",
      voicePlaybackUnavailable: "Voice playback is unavailable in this environment.",
    },
    lostFoundScreen: {
      subtitle: "Your reported items and recent status changes.",
      noItems: "No lost and found items yet.",
      createItem: "Report item",
      title: "Title",
      description: "Description",
      category: "Category",
      lostCategory: "Lost",
      foundCategory: "Found",
      foundLocation: "Found location",
      contactNote: "Contact note",
      commentPlaceholder: "Add a comment",
      createItemBusy: "Reporting item...",
      commentBusy: "Sending comment...",
      itemComments: "Comments",
      addComment: "Add comment",
      media: "Media",
      photos: "Photos",
      addPhotos: "Add photos",
      addPhotosToReport: "Add report photos",
      uploadingPhotos: "Uploading photos...",
      noPhotos: "No photos added yet.",
      photoHint: "Add clear photos so the front desk can identify the item faster.",
      unsupportedPhoto: "This photo format is not supported. Use JPEG, PNG, WebP, HEIC, or HEIF.",
    },
    profileScreen: {
      subtitle: "Customer profile fields and notification preferences.",
      noPhone: "No phone number yet",
      noBio: "No bio yet",
      notificationSettings: "Notification settings",
      push: "Push",
      chat: "Chat",
      support: "Support",
      billing: "Billing",
      fullName: "Full name",
      phone: "Phone number",
      bio: "Bio",
      profilePhoto: "Profile photo",
      changePhoto: "Change photo",
      uploadingPhoto: "Uploading photo...",
      noPhoto: "No profile photo yet",
      saveProfile: "Save profile",
      savingProfile: "Saving profile...",
      currentPassword: "Current password",
      newPassword: "New password",
      changePassword: "Change password",
      changingPassword: "Changing password...",
      announcements: "Announcements",
    },
    feedbackScreen: {
      subtitle: "Workout, diet, and gym feedback submitted from your account.",
      workout: "Workout feedback",
      diet: "Diet feedback",
      gym: "Gym feedback",
      noWorkout: "No workout feedback yet.",
      noDiet: "No diet feedback yet.",
      noGym: "No gym feedback yet.",
      dietPlan: "Diet plan",
      submitGymFeedback: "Submit gym feedback",
      submittingFeedback: "Submitting feedback...",
      feedbackSaved: "Feedback submitted.",
      rating: "Rating",
      commentPlaceholder: "Tell the gym what went well or what needs attention.",
      equipment: "Equipment",
      cleanliness: "Cleanliness",
      staff: "Staff",
      classes: "Classes",
      general: "General",
    },
    session: {
      title: "Starting mobile app",
      subtitle: "Restoring your session and checking gym access.",
      loading: "Loading secure session state...",
    },
  },
  ar: {
    appName: "Gym ERP",
    controls: {
      theme: "المظهر",
      language: "اللغة",
    },
    tabs: {
      home: "الرئيسية",
      qr: "مسح",
      plans: "الخطط",
      progress: "التقدم",
      more: "المزيد",
    },
    common: {
      billing: "الفوترة",
      notifications: "الإشعارات",
      support: "الدعم",
      chat: "المحادثة",
      lostFound: "المفقودات",
      profile: "الملف الشخصي",
      feedbackHistory: "سجل الملاحظات",
      signOut: "تسجيل الخروج",
      noData: "لا توجد بيانات بعد.",
      loading: "جاري التحميل...",
      noActivePlan: "لا توجد خطة نشطة",
      noCurrentPlan: "لا توجد خطة حالية",
      noComment: "لا يوجد تعليق",
      noMessagesYet: "لا توجد رسائل بعد.",
      noLocationAdded: "لم يتم تحديد موقع",
      customer: "العميل",
      coach: "المدرب",
      on: "مفعّل",
      off: "غير مفعّل",
      yes: "نعم",
      no: "لا",
      minutesShort: "د",
      days: "يوم",
      expectedSessions30d: "جلسة متوقعة خلال 30 يوماً",
      unread: "غير المقروء",
      save: "حفظ",
      cancel: "إلغاء",
      send: "إرسال",
      create: "إنشاء",
      update: "تحديث",
      submit: "إرسال",
      reply: "رد",
      note: "ملاحظة",
      message: "الرسالة",
      status: "الحالة",
      category: "الفئة",
      loadingDetails: "جاري تحميل التفاصيل...",
      successUpdated: "تم التحديث بنجاح",
      errorTryAgain: "حدث خطأ. حاول مرة أخرى.",
      attachFile: "إرفاق ملف",
      attachPhoto: "إرفاق صورة",
      attachment: "مرفق",
      uploading: "جارٍ الرفع...",
      photoPermissionDenied: "تم حظر الوصول للصور. فعّله من إعدادات التطبيق.",
    },
    login: {
      title: "Gym ERP",
      subtitle: "وصول العملاء من الجوال للـ QR والخطط والتقدم والدعم.",
      kicker: "تطبيق العملاء - المرحلة الثانية",
      signIn: "تسجيل الدخول",
      signInButton: "دخول",
      signingIn: "جارٍ تسجيل الدخول...",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      localDemo: "حسابات تجريبية محلية",
      localDemoHint: "استخدم حساب العميل المزروع محلياً لتجربة المرحلة الثانية كاملة.",
    },
    home: {
      greeting: "أهلاً",
      subtitle: "لوحة تحكم العميل",
      billingBadge: "الفوترة",
      subscription: "الاشتراك",
      plan: "الخطة",
      status: "الحالة",
      renew: "جدّد من الفوترة",
      workoutPlans: "خطط التمرين",
      dietPlans: "خطط الغذاء",
      checkIns: "مرات الدخول",
      unreadChat: "محادثات غير مقروءة",
      latestBiometric: "آخر قياس",
      weight: "الوزن",
      bodyFat: "دهون الجسم",
      noBiometrics: "لا توجد قياسات بعد.",
      recentReceipts: "آخر الإيصالات",
      noReceipts: "لا توجد إيصالات بعد.",
      quickActions: "إجراءات سريعة",
      logBodyMetrics: "تسجيل القياسات",
      requestSupport: "طلب دعم",
      reportLostItem: "الإبلاغ عن غرض",
      leaveFeedback: "إرسال ملاحظات",
      achievements: "الإنجازات",
      achievementsSubtitle: "إنجازاتك وسلاسل الحضور والشارات المفتوحة.",
      currentStreak: "السلسلة الحالية",
      bestStreak: "أفضل سلسلة",
      totalVisits: "إجمالي الزيارات",
      unlocked: "مفتوحة",
      noBadges: "لا توجد شارات مفتوحة بعد.",
      locked: "مقفلة",
      viewAllBadges: "عرض كل الشارات",
      earnedOn: "تم الحصول عليها",
    },
    qr: {
      title: "مسح الدخول",
      subtitle: "امسح رمز النادي عند الاستقبال أو البوابة أو نقطة تسجيل الدخول.",
      entranceStatus: "حالة الدخول",
      cameraReady: "الكاميرا جاهزة",
      cameraHint: "وجّه الهاتف إلى رمز النادي لمسحه.",
      noPersonalCode: "العميل لا يحمل رمز QR شخصياً داخل التطبيق.",
      grantCamera: "السماح بالكاميرا",
      cameraDenied: "تم حظر الكاميرا. فعّلها من إعدادات التطبيق.",
      scanAgain: "امسح مرة أخرى",
      lastScan: "آخر عملية مسح",
      scannerFrame: "ضع رمز النادي داخل الإطار",
      scanResult: "نتيجة الدخول",
      scanStatus: "حالة المسح",
      scanReason: "السبب",
      scanKiosk: "الجهاز",
      scanTime: "الوقت",
      invalidCode: "رمز QR هذا ليس رمز جهاز نادي صالحاً.",
      scanning: "جارٍ التحقق من الدخول...",
      noReason: "لا يوجد سبب إضافي",
    },
    plans: {
      title: "الخطط",
      subtitle: "خطط التمرين والغذاء المخصصة لك.",
      workoutPlans: "خطط التمرين",
      dietPlans: "خطط الغذاء",
      noWorkoutPlans: "لا توجد خطط تمرين حالياً.",
      noDietPlans: "لا توجد خطط غذاء حالياً.",
      startSession: "ابدأ الجلسة",
      resumeSession: "استئناف الجلسة",
      abandonSession: "إلغاء الجلسة",
      completeExercise: "إكمال التمرين",
      skipExercise: "تخطي التمرين",
      finishSession: "إنهاء الجلسة",
      currentExercise: "التمرين الحالي",
      progress: "التقدم",
      target: "الهدف",
      section: "القسم",
      chooseSection: "اختر القسم",
      setsCompleted: "الجولات المنفذة",
      repsCompleted: "التكرارات المنفذة",
      weightKg: "الوزن (كجم)",
      exerciseNotes: "ملاحظات التمرين",
      sessionNotes: "ملاحظات الجلسة",
      sessionDuration: "مدة الجلسة (دقيقة)",
      prToggle: "هذا إنجاز شخصي",
      prType: "نوع الإنجاز",
      prValue: "قيمة الإنجاز",
      prNotes: "ملاحظات الإنجاز",
      recentSessions: "الجلسات الأخيرة",
      noSessionHistory: "لا توجد جلسات مكتملة بعد.",
      dietTracker: "متتبع النظام الغذائي",
      dayAdherence: "التزام اليوم",
      dayNotes: "ملاحظات اليوم",
      saveDay: "حفظ اليوم",
      noStructuredDiet: "هذه الخطة لا تحتوي على أيام ووجبات منظمة بعد.",
      planContent: "محتوى الخطة",
      markDone: "تمت",
      done: "مكتمل",
      workoutStarted: "تم بدء الجلسة.",
      workoutSaved: "تم حفظ التمرين.",
      workoutSkipped: "تم تخطي التمرين.",
      workoutFinished: "تم إنهاء الجلسة.",
      workoutAbandoned: "تم حذف الجلسة النشطة.",
      dietSaved: "تم تحديث اليوم الغذائي.",
    },
    progress: {
      title: "التقدم",
      subtitle: "القياسات وسجل الحضور وجلسات التمرين.",
      biometrics: "القياسات",
      noBiometrics: "لا يوجد سجل قياسات بعد.",
      recentSessions: "الجلسات الأخيرة",
      noSessions: "لا يوجد سجل جلسات بعد.",
      attendance: "الحضور",
      recentScans: "عملية دخول حديثة",
      thisMonth: "هذا الشهر",
      lastWeight: "آخر وزن",
      lastBodyFat: "آخر نسبة دهون",
      bodyFat: "دهون",
      muscleMass: "عضل",
      workouts30d: "تمارين / 30 يوم",
      attendanceTimeline: "آخر عمليات الدخول",
      workoutTrend: "اتجاه التمرين",
      bodyMetricsTrend: "اتجاه قياسات الجسم",
      weightTrend: "اتجاه الوزن",
      bodyFatTrend: "اتجاه الدهون",
      muscleTrend: "اتجاه العضلات",
      attendanceStats: "إنجازات الحضور",
      prSection: "أرقام التمارين الشخصية",
      noPersonalRecords: "لا توجد أرقام شخصية بعد. سجّل إنجازاً أثناء التمرين وسيظهر هنا.",
      prFallback: "رقم تمرين شخصي",
      latest: "الأحدث",
      range: "النطاق",
      change: "التغير",
      logBodyMetrics: "تسجيل قياسات الجسم",
      saveBodyMetrics: "حفظ القياسات",
      savingBodyMetrics: "جارٍ حفظ القياسات...",
      heightCm: "الطول (سم)",
      weightKg: "الوزن (كجم)",
      bodyFatPct: "دهون الجسم (%)",
      muscleMassKg: "الكتلة العضلية (كجم)",
      metricsSaved: "تم حفظ قياسات الجسم.",
      graphNoData: "أضف قياسات الجسم لتظهر الرسوم هنا.",
      latestSessionNotes: "ملاحظات آخر جلسة",
      noTrend: "لا يوجد اتجاه للتمرين بعد.",
      noAttendance: "لا توجد عمليات دخول بعد.",
      noSessionNotes: "لا توجد ملاحظات جلسة بعد.",
    },
    more: {
      title: "المزيد",
      subtitle: "خدمات العميل والملف الشخصي وإعدادات التطبيق.",
      customerAccount: "حساب العميل",
      billing: "الفوترة وطلبات التجديد",
      notifications: "الإشعارات",
      support: "تذاكر الدعم",
      chat: "المحادثات",
      lostFound: "المفقودات",
      profile: "الملف والإعدادات",
      feedback: "سجل الملاحظات",
    },
    billingScreen: {
      subtitle: "طلبات التجديد والعروض والإيصالات وسياسة الدفع.",
      renewalRequests: "طلبات التجديد",
      noRenewalRequests: "لا توجد طلبات تجديد بعد.",
      renewalOffers: "عروض التجديد",
      receipts: "الإيصالات",
      paymentPolicy: "سياسة الدفع",
      currentPlan: "الخطة الحالية",
      expiryDate: "تاريخ الانتهاء",
      subscriptionRequests: "طلبات الاشتراك",
      requestRenewal: "طلب تجديد",
      requestFreeze: "طلب تجميد",
      requestUnfreeze: "طلب إلغاء التجميد",
      contactSupport: "التواصل مع الدعم",
      requestExtension: "طلب تمديد",
      requestActivationExtend: "طلب تفعيل / تمديد",
      noExpirySet: "لا يوجد تاريخ انتهاء محدد",
      activeTitle: "الاشتراك نشط",
      activeDesc: "خطتك نشطة. يمكنك طلب تمديد أو تجميد من هذه الصفحة.",
      frozenTitle: "الاشتراك مجمّد",
      frozenDesc: "اشتراكك مجمّد حاليًا. اطلب إلغاء التجميد لاستعادة الوصول الكامل.",
      expiredTitle: "الاشتراك منتهي",
      expiredDesc: "انتهت صلاحية الاشتراك. اطلب التجديد أو التمديد للمتابعة.",
      noneTitle: "لا يوجد اشتراك نشط",
      noneDesc: "لا يوجد اشتراك نشط مرتبط بحسابك. اطلب التفعيل أو التمديد.",
      requestTitle: "إرسال طلب تجديد",
      requestHelp: "أرسل طلب التجديد هنا، ثم ادفع نقداً في النادي وانتظر موافقة الموظفين.",
      selectedOffer: "العرض المختار",
      customerNote: "ملاحظة العميل",
      customerNotePlaceholder: "أخبر النادي متى ستدفع أو اترك ملاحظة مفيدة.",
      submitRequest: "إرسال طلب التجديد",
      submittingRequest: "جارٍ إرسال الطلب...",
    },
    notificationsScreen: {
      subtitle: "آخر أحداث العميل وعناصر صندوق الإشعارات.",
    },
    supportScreen: {
      subtitle: "تذاكر دعم العميل والردود الأخيرة.",
      noTickets: "لا توجد تذاكر دعم بعد.",
      newTicket: "إنشاء تذكرة دعم",
      subject: "الموضوع",
      subjectPlaceholder: "عنوان مختصر للمشكلة",
      messagePlaceholder: "اشرح ما الذي تحتاج إليه",
      sendReply: "إرسال الرد",
      sendingReply: "جارٍ إرسال الرد...",
      creatingTicket: "جارٍ إنشاء التذكرة...",
      pickTicket: "اختر تذكرة لمتابعة المحادثة.",
    },
    chatScreen: {
      subtitle: "محادثات المدرب وعدد الرسائل غير المقروءة.",
      subtitleStart: "اختر مدرباً، وابدأ المحادثة، واحتفظ بالردود في مكان واحد.",
      noThreads: "لا توجد محادثات بعد.",
      startThread: "بدء محادثة",
      newConversation: "محادثة جديدة",
      startConversation: "ابدأ المحادثة",
      selectedCoachLabel: "المدرب المحدد:",
      coachId: "المدرب",
      coachIdPlaceholder: "اختر مدرباً",
      openThread: "فتح المحادثة",
      threadMessages: "رسائل المحادثة",
      threadHint: "عرض محادثة مناسب للهاتف",
      emptyState: "اختر محادثة أو ابدأ محادثة جديدة.",
      messagePlaceholder: "اكتب رسالة",
      markRead: "تعيين كمقروء",
      creatingThread: "جارٍ بدء المحادثة...",
      sendingMessage: "جارٍ إرسال الرسالة...",
      pickThread: "اختر محادثة لعرضها كاملة.",
      noCoaches: "لا يوجد مدربون متاحون بعد.",
      threadStarted: "المحادثة جاهزة.",
      unreadActive: "غير مقروء",
      liveNow: "مباشر",
      recording: "جارٍ تسجيل رسالة صوتية...",
      voicePreview: "معاينة الرسالة الصوتية",
      acceptSend: "قبول وإرسال",
      discard: "تجاهل",
      microphoneUnavailable: "تعذر الوصول إلى الميكروفون.",
      voiceUnavailable: "الرسائل الصوتية تحتاج Expo Go أحدث أو نسخة تطوير.",
      voicePlaybackUnavailable: "تشغيل الرسائل الصوتية غير متاح في هذه البيئة.",
    },
    lostFoundScreen: {
      subtitle: "الأغراض التي أبلغت عنها وآخر تحديثات الحالة.",
      noItems: "لا توجد عناصر مفقودات بعد.",
      createItem: "الإبلاغ عن غرض",
      title: "العنوان",
      description: "الوصف",
      category: "الفئة",
      lostCategory: "مفقود",
      foundCategory: "معثور عليه",
      foundLocation: "مكان العثور",
      contactNote: "ملاحظة التواصل",
      commentPlaceholder: "أضف تعليقاً",
      createItemBusy: "جارٍ الإبلاغ عن الغرض...",
      commentBusy: "جارٍ إرسال التعليق...",
      itemComments: "التعليقات",
      addComment: "إضافة تعليق",
      media: "الوسائط",
      photos: "الصور",
      addPhotos: "إضافة صور",
      addPhotosToReport: "أضف صورًا للبلاغ",
      uploadingPhotos: "جارٍ رفع الصور...",
      noPhotos: "لا توجد صور بعد.",
      photoHint: "أضف صورًا واضحة ليسهل على الاستقبال التعرف على الغرض.",
      unsupportedPhoto: "صيغة الصورة غير مدعومة. استخدم JPEG أو PNG أو WebP أو HEIC أو HEIF.",
    },
    profileScreen: {
      subtitle: "بيانات الملف الشخصي وتفضيلات الإشعارات.",
      noPhone: "لا يوجد رقم هاتف بعد",
      noBio: "لا توجد نبذة بعد",
      notificationSettings: "إعدادات الإشعارات",
      push: "الدفع",
      chat: "المحادثة",
      support: "الدعم",
      billing: "الفوترة",
      fullName: "الاسم الكامل",
      phone: "رقم الهاتف",
      bio: "نبذة",
      profilePhoto: "الصورة الشخصية",
      changePhoto: "تغيير الصورة",
      uploadingPhoto: "جارٍ رفع الصورة...",
      noPhoto: "لا توجد صورة شخصية بعد",
      saveProfile: "حفظ الملف",
      savingProfile: "جارٍ حفظ الملف...",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      changePassword: "تغيير كلمة المرور",
      changingPassword: "جارٍ تغيير كلمة المرور...",
      announcements: "الإعلانات",
    },
    feedbackScreen: {
      subtitle: "ملاحظات التمرين والغذاء والنادي المرسلة من حسابك.",
      workout: "ملاحظات التمرين",
      diet: "ملاحظات الغذاء",
      gym: "ملاحظات النادي",
      noWorkout: "لا توجد ملاحظات تمرين بعد.",
      noDiet: "لا توجد ملاحظات غذاء بعد.",
      noGym: "لا توجد ملاحظات للنادي بعد.",
      dietPlan: "خطة غذاء",
      submitGymFeedback: "إرسال ملاحظات للنادي",
      submittingFeedback: "جارٍ إرسال الملاحظات...",
      feedbackSaved: "تم إرسال الملاحظات.",
      rating: "التقييم",
      commentPlaceholder: "أخبر النادي بما كان جيداً أو ما يحتاج إلى اهتمام.",
      equipment: "المعدات",
      cleanliness: "النظافة",
      staff: "الموظفون",
      classes: "الحصص",
      general: "عام",
    },
    session: {
      title: "جارٍ تشغيل التطبيق",
      subtitle: "يتم استرجاع الجلسة والتحقق من الوصول للنادي.",
      loading: "جاري تحميل حالة الجلسة الآمنة...",
    },
  },
} as const;

type PreferencesContextValue = {
  locale: Locale;
  themeMode: ThemeMode;
  direction: "ltr" | "rtl";
  isRTL: boolean;
  theme: ThemeTokens;
  fontSet: {
    display: string;
    body: string;
    mono: string;
  };
  copy: CopySet;
  toggleLocale: () => Promise<void>;
  toggleThemeMode: () => Promise<void>;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: PropsWithChildren) {
  const [locale, setLocale] = useState<Locale>("en");
  const [themeMode, setThemeMode] = useState<ThemeMode>("light");

  useEffect(() => {
    let alive = true;
    async function restore() {
      const storedLocale = await SecureStore.getItemAsync(LOCALE_STORAGE_KEY);
      const storedTheme = await SecureStore.getItemAsync(THEME_STORAGE_KEY);
      if (!alive) {
        return;
      }
      if (storedLocale === "en" || storedLocale === "ar") {
        setLocale(storedLocale);
      }
      if (storedTheme === "light" || storedTheme === "dark") {
        setThemeMode(storedTheme);
      }
    }
    void restore();
    return () => {
      alive = false;
    };
  }, []);

  async function toggleLocale() {
    const next = locale === "en" ? "ar" : "en";
    setLocale(next);
    await SecureStore.setItemAsync(LOCALE_STORAGE_KEY, next);
  }

  async function toggleThemeMode() {
    const next = themeMode === "light" ? "dark" : "light";
    setThemeMode(next);
    await SecureStore.setItemAsync(THEME_STORAGE_KEY, next);
  }

  const value = useMemo<PreferencesContextValue>(() => {
    const direction = locale === "ar" ? "rtl" : "ltr";
    return {
      locale,
      themeMode,
      direction,
      isRTL: direction === "rtl",
      theme: themes[themeMode],
      fontSet: fonts[locale] as { display: string; body: string; mono: string },
      copy: copy[locale],
      toggleLocale,
      toggleThemeMode,
    };
  }, [locale, themeMode]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error("usePreferences must be used within PreferencesProvider");
  }
  return context;
}
