import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from "react";
import * as SecureStore from "expo-secure-store";

import { fonts, themes, type Locale, type ThemeMode } from "@/lib/theme";

type ThemeTokens = (typeof themes)[keyof typeof themes];
type CopySet = (typeof copy)[keyof typeof copy];

const THEME_STORAGE_KEY = "gym-erp.mobile.theme";
const LOCALE_STORAGE_KEY = "gym-erp.mobile.locale";

const copy = {
  en: {
    appName: "Gym ERP",
    controls: {
      theme: "Theme",
      language: "Language",
    },
    tabs: {
      home: "Home",
      qr: "Scan",
      plans: "Plans",
      progress: "Progress",
      more: "More",
    },
    staffTabs: {
      checkIn: "Check-in",
      members: "Members",
      pos: "POS",
      transactions: "Transactions",
      tasks: "Tasks",
      finance: "Finance",
    },
    common: {
      billing: "Billing",
      notifications: "Notifications",
      support: "Support",
      chat: "Chat",
      lostFound: "Lost & Found",
      profile: "Profile",
      feedbackHistory: "Feedback History",
      signOut: "Sign out",
      noData: "No data yet.",
      loading: "Loading...",
      noActivePlan: "No active plan",
      noCurrentPlan: "No current plan",
      noComment: "No comment",
      noMessagesYet: "No messages yet.",
      noLocationAdded: "No location added",
      customer: "Customer",
      coach: "Coach",
      on: "On",
      off: "Off",
      yes: "Yes",
      no: "No",
      minutesShort: "min",
      days: "days",
      expectedSessions30d: "expected sessions / 30d",
      unread: "Unread",
      save: "Save",
      cancel: "Cancel",
      send: "Send",
      create: "Create",
      open: "Open",
      update: "Update",
      submit: "Submit",
      reply: "Reply",
      note: "Note",
      message: "Message",
      status: "Status",
      category: "Category",
      loadingDetails: "Loading details...",
      successUpdated: "Updated successfully",
      errorTryAgain: "Something went wrong. Please try again.",
      attachFile: "Attach file",
      attachPhoto: "Attach photo",
      attachment: "Attachment",
      uploading: "Uploading...",
      photoPermissionDenied: "Photo library access is blocked. Enable it from app settings.",
    },
    login: {
      title: "Gym ERP",
      subtitle: "Customer mobile access for QR entry, plans, progress, and support.",
      kicker: "Phase 2 customer app",
      signIn: "Sign in",
      signInButton: "Continue",
      signingIn: "Signing in...",
      email: "Email",
      password: "Password",
      localDemo: "Local demo accounts",
      localDemoHint: "Use the seeded customer account for a full Phase 2 walkthrough.",
    },
    home: {
      greeting: "Hi",
      subtitle: "Customer control center",
      billingBadge: "Billing",
      subscription: "Subscription",
      plan: "Plan",
      status: "Status",
      renew: "Renew from billing",
      workoutPlans: "Workout plans",
      dietPlans: "Diet plans",
      checkIns: "Check-ins",
      unreadChat: "Unread chat",
      latestBiometric: "Latest biometric",
      weight: "Weight",
      bodyFat: "Body fat",
      noBiometrics: "No biometric logs yet.",
      recentReceipts: "Recent receipts",
      noReceipts: "No receipts yet.",
      quickActions: "Quick actions",
      logBodyMetrics: "Log body metrics",
      requestSupport: "Request support",
      reportLostItem: "Report lost item",
      leaveFeedback: "Leave feedback",
      achievements: "Achievements",
      achievementsSubtitle: "Your gym milestones, streaks, and unlocked badges.",
      currentStreak: "Current streak",
      bestStreak: "Best streak",
      totalVisits: "Total visits",
      unlocked: "unlocked",
      noBadges: "No badges unlocked yet.",
      locked: "Locked",
      viewAllBadges: "View all badges",
      earnedOn: "Earned",
    },
    qr: {
      title: "Check-in Scan",
      subtitle: "Scan the gym QR shown at reception, the gate, or the check-in point.",
      entranceStatus: "Entrance status",
      cameraReady: "Camera is ready",
      cameraHint: "Point your phone at the gym QR to scan it.",
      noPersonalCode: "Customers do not carry their own QR code in the app.",
      grantCamera: "Allow camera",
      cameraDenied: "Camera access is blocked. Enable it from app settings.",
      scanAgain: "Scan again",
      lastScan: "Last scan",
      scannerFrame: "Align the gym QR inside the frame",
      scanResult: "Check-in result",
      scanStatus: "Scan status",
      scanReason: "Reason",
      scanKiosk: "Kiosk",
      scanTime: "Time",
      invalidCode: "This QR code is not a valid gym kiosk code.",
      staffOnlyCode: "This QR is for staff attendance.",
      staffShiftTitle: "Shift scanner",
      staffShiftHint: "Scan the staff start or end QR from the web entrance QR page.",
      staffScreenSubtitle: "Start or finish your shift here. If you scan an entrance QR, you can also use it for member check-in.",
      staffShiftDetected: "Ready to record shift action",
      staffMemberCheckInTitle: "Member check-in",
      staffMemberCheckInHint: "Scan or enter the entrance kiosk first, then pick a member to check in.",
      staffMemberSearchHint: "Search by member name, email, or phone. Results appear below as you type.",
      staffMemberKioskReady: "Entrance kiosk ready",
      staffMemberKioskMissing: "Scan an entrance QR or type a kiosk ID to enable member check-in.",
      staffSelectedMember: "Selected member",
      staffStart: "Start shift",
      staffEnd: "Finish shift",
      staffShiftResult: "Shift result",
      manualKiosk: "Manual kiosk ID",
      scanning: "Checking access...",
      noReason: "No additional reason",
    },
    plans: {
      title: "Plans",
      subtitle: "Your assigned workout and diet plans.",
      workoutPlans: "Workout plans",
      dietPlans: "Diet plans",
      noWorkoutPlans: "No workout plans assigned.",
      noDietPlans: "No diet plans assigned.",
      startSession: "Start session",
      resumeSession: "Resume session",
      abandonSession: "Abandon session",
      completeExercise: "Complete exercise",
      skipExercise: "Skip exercise",
      finishSession: "Finish session",
      currentExercise: "Current exercise",
      progress: "Progress",
      target: "Target",
      section: "Section",
      chooseSection: "Choose section",
      setsCompleted: "Sets completed",
      repsCompleted: "Reps completed",
      weightKg: "Weight (kg)",
      exerciseNotes: "Exercise notes",
      sessionNotes: "Session notes",
      sessionDuration: "Session duration (min)",
      prToggle: "This was a PR",
      prType: "PR type",
      prValue: "PR value",
      prNotes: "PR notes",
      recentSessions: "Recent sessions",
      noSessionHistory: "No completed sessions yet.",
      dietTracker: "Diet tracker",
      dayAdherence: "Daily adherence",
      dayNotes: "Day notes",
      saveDay: "Save day",
      noStructuredDiet: "This diet does not have structured days and meals yet.",
      planContent: "Plan content",
      markDone: "Mark done",
      done: "Done",
      workoutStarted: "Workout session started.",
      workoutSaved: "Exercise logged.",
      workoutSkipped: "Exercise skipped.",
      workoutFinished: "Workout session finished.",
      workoutAbandoned: "Active workout session discarded.",
      dietSaved: "Diet day updated.",
    },
    progress: {
      title: "Progress",
      subtitle: "Biometrics, attendance history, and workout sessions.",
      biometrics: "Biometrics",
      noBiometrics: "No biometric history yet.",
      recentSessions: "Recent sessions",
      noSessions: "No session logs yet.",
      attendance: "Attendance",
      recentScans: "recent access scans",
      thisMonth: "This month",
      lastWeight: "Last weight",
      lastBodyFat: "Last body fat",
      bodyFat: "body fat",
      muscleMass: "muscle",
      workouts30d: "Workouts / 30d",
      attendanceTimeline: "Recent check-ins",
      workoutTrend: "Workout trend",
      bodyMetricsTrend: "Body metrics trend",
      weightTrend: "Weight trend",
      bodyFatTrend: "Body fat trend",
      muscleTrend: "Muscle trend",
      attendanceStats: "Attendance milestones",
      prSection: "Exercise PRs",
      noPersonalRecords: "No PRs logged yet. Mark a PR during a workout session and it will appear here.",
      prFallback: "Exercise PR",
      latest: "Latest",
      range: "Range",
      change: "Change",
      logBodyMetrics: "Log body metrics",
      saveBodyMetrics: "Save body metrics",
      savingBodyMetrics: "Saving metrics...",
      heightCm: "Height (cm)",
      weightKg: "Weight (kg)",
      bodyFatPct: "Body fat (%)",
      muscleMassKg: "Muscle mass (kg)",
      metricsSaved: "Body metrics saved.",
      graphNoData: "Add body metrics to see graphs here.",
      latestSessionNotes: "Latest session notes",
      noTrend: "No workout trend yet.",
      noAttendance: "No check-ins yet.",
      noSessionNotes: "No session notes yet.",
    },
    more: {
      title: "More",
      subtitle: "Customer services, profile, and app settings.",
      customerAccount: "Customer account",
      billing: "Billing and renewal requests",
      notifications: "Notifications",
      support: "Support tickets",
      chat: "Chat threads",
      lostFound: "Lost & Found",
      profile: "Profile and settings",
      feedback: "Feedback history",
    },
    staffMore: {
      account: "Staff account",
      noAssignedPlan: "No assigned plan",
    },
    staffHome: {
      title: "Operations",
      subtitle: "Role-aware staff dashboard",
      activity: "Recent activity",
      shiftStatus: "Shift status",
      shiftStartedAt: "Started at",
      shiftNotStarted: "Not clocked in yet.",
      headlines: {
        ADMIN: "Admin operations",
        MANAGER: "Manager operations",
        COACH: "Coach control center",
        RECEPTION: "Front desk overview",
        FRONT_DESK: "Front desk overview",
        CASHIER: "Cashier sales desk",
        EMPLOYEE: "Personal operations",
      },
      actions: {
        members: "Members",
        plans: "Plans",
        feedback: "Feedback",
        leaves: "Leaves",
        chat: "Chat",
        checkin: "Check-in",
        support: "Support",
        pos: "POS",
        transactions: "Transactions",
        qr: "QR",
        shift_qr: "Start/finish shift",
        tasks: "Tasks",
        profile: "Profile",
      },
      items: {
        attendance: "Attendance",
        clockedIn: "Clocked in",
        notClockedIn: "Not clocked in",
        member: "Member",
      },
      stats: {
        assigned_members: "Assigned members",
        active_workout_plans: "Workout plans",
        active_diet_plans: "Diet plans",
        feedback_items: "Feedback",
        today_sessions: "Today sessions",
        members: "Members",
        open_support_tickets: "Support queue",
        open_lost_found: "Lost & Found",
        recent_scans: "Recent scans",
        today_sales_total: "Sales total",
        today_sales_count: "Sales",
        low_stock_count: "Low stock",
        clocked_in: "Clocked in",
        upcoming_leaves: "Leaves",
        lost_found_enabled: "Lost & Found",
      },
    },
    membersScreen: {
      title: "Members",
      subtitle: "Lookup members and review subscription, attendance, and plans.",
      search: "Search by name, email, or phone",
      searchMoreHint: "Showing the first 50 matches. Search by name, email, or phone to find more.",
      noMembers: "No members found.",
      workoutPlans: "Workout plans",
      dietPlans: "Diet plans",
      attendance: "Recent attendance",
      biometrics: "Biometric trend",
      progressHistory: "Workout history",
      workoutFeedback: "Workout feedback",
      dietFeedback: "Diet feedback",
      gymFeedback: "Gym feedback",
      assignWorkout: "Assign workout",
      assignDiet: "Assign diet",
      pickWorkout: "Pick a workout plan below to assign.",
      pickDiet: "Pick a diet plan below to assign.",
      pickMember: "Pick a member to review details.",
      feedback: "Feedback",
      noAssignablePlans: "No assignable workout plans found.",
      noAssignableDiets: "No assignable diet plans found.",
      showMore: "more",
      showLess: "Show less",
      openChat: "Message member",
      checkInMember: "Check in member",
      openSupport: "Open support",
      viewFeedbackQueue: "Open feedback queue",
      quickRegister: "Quick register",
      quickRegisterSubtitle: "Create a customer account from mobile. Subscription setup stays separate.",
      newMember: "New member",
      fullName: "Full name",
      email: "Email",
      phoneNumber: "Phone number",
      temporaryPassword: "Temporary password",
      createMember: "Create member",
    },
    financeScreen: {
      title: "POS",
      subtitle: "Products, checkout, and recent POS activity.",
      todaySales: "Today sales",
      lowStock: "Low stock",
      products: "Products",
      noProducts: "No products available.",
      sell: "Sell 1 item",
      recentTransactions: "Recent transactions",
      memberId: "Member ID (optional)",
    },
    operationsScreen: {
      title: "Operations",
      subtitle: "Transactions, leaves, and quick staff actions.",
      recentTransactions: "Recent transactions",
      noTransactions: "No recent transactions.",
      myLeaves: "My leaves",
      noLeaves: "No leave requests yet.",
      openProfile: "Open profile",
      openLostFound: "Open Lost & Found",
    },
    billingScreen: {
      subtitle: "Renewal requests, offers, receipts, and payment policy.",
      renewalRequests: "Renewal requests",
      noRenewalRequests: "No renewal requests yet.",
      renewalOffers: "Renewal offers",
      receipts: "Receipts",
      paymentPolicy: "Payment policy",
      currentPlan: "Current plan",
      expiryDate: "Expiry date",
      subscriptionRequests: "Subscription requests",
      requestRenewal: "Request renewal",
      requestFreeze: "Request freeze",
      requestUnfreeze: "Request unfreeze",
      contactSupport: "Contact support",
      requestExtension: "Request extension",
      requestActivationExtend: "Request activation / extend",
      noExpirySet: "No expiry date set",
      activeTitle: "Subscription active",
      activeDesc: "Your plan is active. You can request an extension or freeze from this page.",
      frozenTitle: "Subscription frozen",
      frozenDesc: "Your subscription is frozen. Request unfreeze to restore full access.",
      expiredTitle: "Subscription expired",
      expiredDesc: "Your subscription has expired. Request renewal or extension to continue.",
      noneTitle: "No active subscription",
      noneDesc: "No active subscription is linked to your account. Request activation or extension.",
      requestTitle: "Submit renewal request",
      requestHelp: "Send your renewal request here, then pay at the gym in cash and wait for staff approval.",
      selectedOffer: "Selected offer",
      customerNote: "Customer note",
      customerNotePlaceholder: "Tell the gym when you plan to pay or leave any helpful note.",
      submitRequest: "Submit renewal request",
      submittingRequest: "Submitting request...",
    },
    notificationsScreen: {
      subtitle: "Recent customer events and inbox items.",
    },
    supportScreen: {
      subtitle: "Open customer support tickets and recent replies.",
      noTickets: "No support tickets yet.",
      newTicket: "Create support ticket",
      subject: "Subject",
      subjectPlaceholder: "Short title for your issue",
      messagePlaceholder: "Explain what you need help with",
      sendReply: "Send reply",
      sendingReply: "Sending reply...",
      creatingTicket: "Creating ticket...",
      pickTicket: "Pick a ticket to continue the conversation.",
    },
    chatScreen: {
      subtitle: "Coach conversations and unread thread counts.",
      subtitleStart: "Pick a coach, start a thread, and keep replies in one place.",
      noThreads: "No chat threads yet.",
      startThread: "Start chat",
      newConversation: "New conversation",
      startConversation: "Start conversation",
      selectedContactLabel: "Selected contact:",
      selectedCoachLabel: "Selected coach:",
      searchContactsPlaceholder: "Search by name or email",
      contactPickerPlaceholder: "Choose a contact",
      searchThreadsPlaceholder: "Search chats",
      threadPickerPlaceholder: "Choose a conversation",
      coachId: "Coach",
      coachIdPlaceholder: "Choose a coach",
      openThread: "Open thread",
      threadMessages: "Thread messages",
      threadHint: "Phone-style conversation view",
      emptyState: "Pick a thread or start a new conversation.",
      messagePlaceholder: "Write a message",
      markRead: "Mark as read",
      creatingThread: "Starting chat...",
      sendingMessage: "Sending message...",
      pickThread: "Pick a thread to see the full conversation.",
      noCoaches: "No coaches available yet.",
      noMatchingContacts: "No matching contacts.",
      noMatchingThreads: "No matching conversations.",
      threadStarted: "Chat is ready.",
      unreadActive: "Unread",
      liveNow: "Live",
      recording: "Recording voice note...",
      voicePreview: "Voice note preview",
      acceptSend: "Accept & Send",
      discard: "Discard",
      microphoneUnavailable: "Unable to access microphone.",
      voiceUnavailable: "Voice notes need a newer Expo Go or a development build.",
      voicePlaybackUnavailable: "Voice playback is unavailable in this environment.",
    },
    lostFoundScreen: {
      subtitle: "Your reported items and recent status changes.",
      noItems: "No lost and found items yet.",
      createItem: "Report item",
      title: "Title",
      description: "Description",
      category: "Category",
      lostCategory: "Lost",
      foundCategory: "Found",
      foundLocation: "Found location",
      contactNote: "Contact note",
      commentPlaceholder: "Add a comment",
      createItemBusy: "Reporting item...",
      commentBusy: "Sending comment...",
      itemComments: "Comments",
      addComment: "Add comment",
      media: "Media",
      photos: "Photos",
      addPhotos: "Add photos",
      addPhotosToReport: "Add report photos",
      uploadingPhotos: "Uploading photos...",
      noPhotos: "No photos added yet.",
      photoHint: "Add clear photos so the front desk can identify the item faster.",
      unsupportedPhoto: "This photo format is not supported. Use JPEG, PNG, WebP, HEIC, or HEIF.",
    },
    profileScreen: {
      subtitle: "Customer profile fields and notification preferences.",
      noPhone: "No phone number yet",
      noBio: "No bio yet",
      notificationSettings: "Notification settings",
      push: "Push",
      chat: "Chat",
      support: "Support",
      billing: "Billing",
      fullName: "Full name",
      phone: "Phone number",
      bio: "Bio",
      profilePhoto: "Profile photo",
      changePhoto: "Change photo",
      uploadingPhoto: "Uploading photo...",
      noPhoto: "No profile photo yet",
      saveProfile: "Save profile",
      savingProfile: "Saving profile...",
      currentPassword: "Current password",
      newPassword: "New password",
      changePassword: "Change password",
      changingPassword: "Changing password...",
      announcements: "Announcements",
    },
    feedbackScreen: {
      subtitle: "Workout, diet, and gym feedback submitted from your account.",
      workout: "Workout feedback",
      diet: "Diet feedback",
      gym: "Gym feedback",
      noWorkout: "No workout feedback yet.",
      noDiet: "No diet feedback yet.",
      noGym: "No gym feedback yet.",
      dietPlan: "Diet plan",
      submitGymFeedback: "Submit gym feedback",
      submittingFeedback: "Submitting feedback...",
      feedbackSaved: "Feedback submitted.",
      rating: "Rating",
      commentPlaceholder: "Tell the gym what went well or what needs attention.",
      equipment: "Equipment",
      cleanliness: "Cleanliness",
      staff: "Staff",
      classes: "Classes",
      general: "General",
      coachSubtitle: "Coach review queue for member workout, diet, and gym feedback.",
      member: "Member",
      openMember: "Open member",
    },
    leavesScreen: {
      subtitle: "Leave requests and time away planning.",
      myLeaves: "My leave requests",
      noLeaves: "No leave requests yet.",
      requestLeave: "Request leave",
      leaveType: "Leave type",
      startDate: "Start date",
      endDate: "End date",
      reason: "Reason",
      submitting: "Submitting leave...",
      submitted: "Leave request submitted.",
    },
    coachPlans: {
      subtitle: "Create, edit, publish, archive, and assign coach plans.",
      createWorkout: "Create workout plan",
      createDiet: "Create diet plan",
      workoutName: "Workout plan name",
      dietName: "Diet plan name",
      description: "Description",
      expectedSessions: "Expected sessions / 30d",
      exercisesHint: "One exercise per line: Section | Exercise | Sets | Reps",
      dietContentHint: "Diet content or meal notes",
      saveDraft: "Save draft",
      saveChanges: "Save changes",
      publish: "Publish",
      archive: "Archive",
      forkDraft: "Fork draft",
      clone: "Clone",
      addExercise: "Add exercise",
      addDay: "Add day",
      addMeal: "Add meal",
      sectionName: "Section",
      exerciseName: "Exercise",
      sets: "Sets",
      reps: "Reps",
      dayName: "Day",
      mealName: "Meal",
      mealItems: "Meal items",
      instructions: "Instructions",
      coachNotes: "Coach notes",
      assignedTo: "Assigned to",
      template: "Template",
      noWorkoutPlans: "No coach workout plans yet.",
      noDietPlans: "No coach diet plans yet.",
      editing: "Editing",
    },
    session: {
      title: "Starting mobile app",
      subtitle: "Restoring your session and checking gym access.",
      loading: "Loading secure session state...",
    },
  },
  ar: {
    appName: "Gym ERP",
    controls: {
      theme: "المظهر",
      language: "اللغة",
    },
    tabs: {
      home: "الرئيسية",
      qr: "مسح",
      plans: "الخطط",
      progress: "التقدم",
      more: "المزيد",
    },
    staffTabs: {
      checkIn: "تسجيل الدخول",
      members: "الأعضاء",
      pos: "نقطة البيع",
      transactions: "المعاملات",
      tasks: "المهام",
      finance: "المالية",
    },
    common: {
      billing: "الفوترة",
      notifications: "الإشعارات",
      support: "الدعم",
      chat: "المحادثة",
      lostFound: "المفقودات",
      profile: "الملف الشخصي",
      feedbackHistory: "سجل الملاحظات",
      signOut: "تسجيل الخروج",
      noData: "لا توجد بيانات بعد.",
      loading: "جاري التحميل...",
      noActivePlan: "لا توجد خطة نشطة",
      noCurrentPlan: "لا توجد خطة حالية",
      noComment: "لا يوجد تعليق",
      noMessagesYet: "لا توجد رسائل بعد.",
      noLocationAdded: "لم يتم تحديد موقع",
      customer: "العميل",
      coach: "المدرب",
      on: "مفعّل",
      off: "غير مفعّل",
      yes: "نعم",
      no: "لا",
      minutesShort: "د",
      days: "يوم",
      expectedSessions30d: "جلسة متوقعة خلال 30 يوماً",
      unread: "غير المقروء",
      save: "حفظ",
      cancel: "إلغاء",
      send: "إرسال",
      create: "إنشاء",
      open: "فتح",
      update: "تحديث",
      submit: "إرسال",
      reply: "رد",
      note: "ملاحظة",
      message: "الرسالة",
      status: "الحالة",
      category: "الفئة",
      loadingDetails: "جاري تحميل التفاصيل...",
      successUpdated: "تم التحديث بنجاح",
      errorTryAgain: "حدث خطأ. حاول مرة أخرى.",
      attachFile: "إرفاق ملف",
      attachPhoto: "إرفاق صورة",
      attachment: "مرفق",
      uploading: "جارٍ الرفع...",
      photoPermissionDenied: "تم حظر الوصول للصور. فعّله من إعدادات التطبيق.",
    },
    login: {
      title: "Gym ERP",
      subtitle: "وصول العملاء من الجوال للـ QR والخطط والتقدم والدعم.",
      kicker: "تطبيق العملاء - المرحلة الثانية",
      signIn: "تسجيل الدخول",
      signInButton: "دخول",
      signingIn: "جارٍ تسجيل الدخول...",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      localDemo: "حسابات تجريبية محلية",
      localDemoHint: "استخدم حساب العميل المزروع محلياً لتجربة المرحلة الثانية كاملة.",
    },
    home: {
      greeting: "أهلاً",
      subtitle: "لوحة تحكم العميل",
      billingBadge: "الفوترة",
      subscription: "الاشتراك",
      plan: "الخطة",
      status: "الحالة",
      renew: "جدّد من الفوترة",
      workoutPlans: "خطط التمرين",
      dietPlans: "خطط الغذاء",
      checkIns: "مرات الدخول",
      unreadChat: "محادثات غير مقروءة",
      latestBiometric: "آخر قياس",
      weight: "الوزن",
      bodyFat: "دهون الجسم",
      noBiometrics: "لا توجد قياسات بعد.",
      recentReceipts: "آخر الإيصالات",
      noReceipts: "لا توجد إيصالات بعد.",
      quickActions: "إجراءات سريعة",
      logBodyMetrics: "تسجيل القياسات",
      requestSupport: "طلب دعم",
      reportLostItem: "الإبلاغ عن غرض",
      leaveFeedback: "إرسال ملاحظات",
      achievements: "الإنجازات",
      achievementsSubtitle: "إنجازاتك وسلاسل الحضور والشارات المفتوحة.",
      currentStreak: "السلسلة الحالية",
      bestStreak: "أفضل سلسلة",
      totalVisits: "إجمالي الزيارات",
      unlocked: "مفتوحة",
      noBadges: "لا توجد شارات مفتوحة بعد.",
      locked: "مقفلة",
      viewAllBadges: "عرض كل الشارات",
      earnedOn: "تم الحصول عليها",
    },
    qr: {
      title: "مسح الدخول",
      subtitle: "امسح رمز النادي عند الاستقبال أو البوابة أو نقطة تسجيل الدخول.",
      entranceStatus: "حالة الدخول",
      cameraReady: "الكاميرا جاهزة",
      cameraHint: "وجّه الهاتف إلى رمز النادي لمسحه.",
      noPersonalCode: "العميل لا يحمل رمز QR شخصياً داخل التطبيق.",
      grantCamera: "السماح بالكاميرا",
      cameraDenied: "تم حظر الكاميرا. فعّلها من إعدادات التطبيق.",
      scanAgain: "امسح مرة أخرى",
      lastScan: "آخر عملية مسح",
      scannerFrame: "ضع رمز النادي داخل الإطار",
      scanResult: "نتيجة الدخول",
      scanStatus: "حالة المسح",
      scanReason: "السبب",
      scanKiosk: "الجهاز",
      scanTime: "الوقت",
      invalidCode: "رمز QR هذا ليس رمز جهاز نادي صالحاً.",
      staffOnlyCode: "هذا الرمز مخصص لحضور الموظفين.",
      staffShiftTitle: "ماسح الدوام",
      staffShiftHint: "امسح رمز بدء أو إنهاء دوام الموظفين من صفحة QR للمدخل في الويب.",
      staffScreenSubtitle: "ابدأ أو أنهِ دوامك من هنا. وإذا مسحت رمز دخول النادي يمكنك استخدامه أيضًا لتسجيل دخول عضو.",
      staffShiftDetected: "جاهز لتسجيل إجراء الدوام",
      staffMemberCheckInTitle: "تسجيل دخول عضو",
      staffMemberCheckInHint: "امسح أو أدخل جهاز الدخول أولاً، ثم اختر العضو لتسجيل دخوله.",
      staffMemberSearchHint: "ابحث باسم العضو أو بريده أو هاتفه. ستظهر النتائج بالأسفل أثناء الكتابة.",
      staffMemberKioskReady: "جهاز الدخول جاهز",
      staffMemberKioskMissing: "امسح رمز دخول النادي أو اكتب معرّف الجهاز لتفعيل تسجيل دخول العضو.",
      staffSelectedMember: "العضو المحدد",
      staffStart: "بدء الدوام",
      staffEnd: "إنهاء الدوام",
      staffShiftResult: "نتيجة الدوام",
      manualKiosk: "معرّف الجهاز اليدوي",
      scanning: "جارٍ التحقق من الدخول...",
      noReason: "لا يوجد سبب إضافي",
    },
    plans: {
      title: "الخطط",
      subtitle: "خطط التمرين والغذاء المخصصة لك.",
      workoutPlans: "خطط التمرين",
      dietPlans: "خطط الغذاء",
      noWorkoutPlans: "لا توجد خطط تمرين حالياً.",
      noDietPlans: "لا توجد خطط غذاء حالياً.",
      startSession: "ابدأ الجلسة",
      resumeSession: "استئناف الجلسة",
      abandonSession: "إلغاء الجلسة",
      completeExercise: "إكمال التمرين",
      skipExercise: "تخطي التمرين",
      finishSession: "إنهاء الجلسة",
      currentExercise: "التمرين الحالي",
      progress: "التقدم",
      target: "الهدف",
      section: "القسم",
      chooseSection: "اختر القسم",
      setsCompleted: "الجولات المنفذة",
      repsCompleted: "التكرارات المنفذة",
      weightKg: "الوزن (كجم)",
      exerciseNotes: "ملاحظات التمرين",
      sessionNotes: "ملاحظات الجلسة",
      sessionDuration: "مدة الجلسة (دقيقة)",
      prToggle: "هذا إنجاز شخصي",
      prType: "نوع الإنجاز",
      prValue: "قيمة الإنجاز",
      prNotes: "ملاحظات الإنجاز",
      recentSessions: "الجلسات الأخيرة",
      noSessionHistory: "لا توجد جلسات مكتملة بعد.",
      dietTracker: "متتبع النظام الغذائي",
      dayAdherence: "التزام اليوم",
      dayNotes: "ملاحظات اليوم",
      saveDay: "حفظ اليوم",
      noStructuredDiet: "هذه الخطة لا تحتوي على أيام ووجبات منظمة بعد.",
      planContent: "محتوى الخطة",
      markDone: "تمت",
      done: "مكتمل",
      workoutStarted: "تم بدء الجلسة.",
      workoutSaved: "تم حفظ التمرين.",
      workoutSkipped: "تم تخطي التمرين.",
      workoutFinished: "تم إنهاء الجلسة.",
      workoutAbandoned: "تم حذف الجلسة النشطة.",
      dietSaved: "تم تحديث اليوم الغذائي.",
    },
    progress: {
      title: "التقدم",
      subtitle: "القياسات وسجل الحضور وجلسات التمرين.",
      biometrics: "القياسات",
      noBiometrics: "لا يوجد سجل قياسات بعد.",
      recentSessions: "الجلسات الأخيرة",
      noSessions: "لا يوجد سجل جلسات بعد.",
      attendance: "الحضور",
      recentScans: "عملية دخول حديثة",
      thisMonth: "هذا الشهر",
      lastWeight: "آخر وزن",
      lastBodyFat: "آخر نسبة دهون",
      bodyFat: "دهون",
      muscleMass: "عضل",
      workouts30d: "تمارين / 30 يوم",
      attendanceTimeline: "آخر عمليات الدخول",
      workoutTrend: "اتجاه التمرين",
      bodyMetricsTrend: "اتجاه قياسات الجسم",
      weightTrend: "اتجاه الوزن",
      bodyFatTrend: "اتجاه الدهون",
      muscleTrend: "اتجاه العضلات",
      attendanceStats: "إنجازات الحضور",
      prSection: "أرقام التمارين الشخصية",
      noPersonalRecords: "لا توجد أرقام شخصية بعد. سجّل إنجازاً أثناء التمرين وسيظهر هنا.",
      prFallback: "رقم تمرين شخصي",
      latest: "الأحدث",
      range: "النطاق",
      change: "التغير",
      logBodyMetrics: "تسجيل قياسات الجسم",
      saveBodyMetrics: "حفظ القياسات",
      savingBodyMetrics: "جارٍ حفظ القياسات...",
      heightCm: "الطول (سم)",
      weightKg: "الوزن (كجم)",
      bodyFatPct: "دهون الجسم (%)",
      muscleMassKg: "الكتلة العضلية (كجم)",
      metricsSaved: "تم حفظ قياسات الجسم.",
      graphNoData: "أضف قياسات الجسم لتظهر الرسوم هنا.",
      latestSessionNotes: "ملاحظات آخر جلسة",
      noTrend: "لا يوجد اتجاه للتمرين بعد.",
      noAttendance: "لا توجد عمليات دخول بعد.",
      noSessionNotes: "لا توجد ملاحظات جلسة بعد.",
    },
    more: {
      title: "المزيد",
      subtitle: "خدمات العميل والملف الشخصي وإعدادات التطبيق.",
      customerAccount: "حساب العميل",
      billing: "الفوترة وطلبات التجديد",
      notifications: "الإشعارات",
      support: "تذاكر الدعم",
      chat: "المحادثات",
      lostFound: "المفقودات",
      profile: "الملف والإعدادات",
      feedback: "سجل الملاحظات",
    },
    staffMore: {
      account: "حساب الموظف",
      noAssignedPlan: "لا توجد خطة مرتبطة",
    },
    staffHome: {
      title: "العمليات",
      subtitle: "لوحة موظفين حسب الدور",
      activity: "النشاط الأخير",
      shiftStatus: "حالة الدوام",
      shiftStartedAt: "بدأ في",
      shiftNotStarted: "لم يبدأ الدوام بعد.",
      headlines: {
        ADMIN: "عمليات المدير",
        MANAGER: "عمليات المشرف",
        COACH: "مركز تحكم المدرب",
        RECEPTION: "نظرة الاستقبال",
        FRONT_DESK: "نظرة الاستقبال",
        CASHIER: "مكتب مبيعات الكاشير",
        EMPLOYEE: "عملياتي",
      },
      actions: {
        members: "الأعضاء",
        plans: "الخطط",
        feedback: "الملاحظات",
        leaves: "الإجازات",
        chat: "المحادثة",
        checkin: "تسجيل الدخول",
        support: "الدعم",
        pos: "نقطة البيع",
        transactions: "المعاملات",
        qr: "QR",
        shift_qr: "بدء/إنهاء الدوام",
        tasks: "المهام",
        profile: "الملف الشخصي",
      },
      items: {
        attendance: "الحضور",
        clockedIn: "مسجل حضور",
        notClockedIn: "غير مسجل حضور",
        member: "عضو",
      },
      stats: {
        assigned_members: "الأعضاء المكلّفون",
        active_workout_plans: "خطط التمرين",
        active_diet_plans: "خطط التغذية",
        feedback_items: "الملاحظات",
        today_sessions: "جلسات اليوم",
        members: "الأعضاء",
        open_support_tickets: "طابور الدعم",
        open_lost_found: "المفقودات",
        recent_scans: "عمليات المسح",
        today_sales_total: "إجمالي المبيعات",
        today_sales_count: "المبيعات",
        low_stock_count: "مخزون منخفض",
        clocked_in: "مسجل حضور",
        upcoming_leaves: "الإجازات",
        lost_found_enabled: "المفقودات",
      },
    },
    membersScreen: {
      title: "الأعضاء",
      subtitle: "ابحث عن الأعضاء واعرض الاشتراك والحضور والخطط.",
      search: "ابحث بالاسم أو البريد أو الهاتف",
      searchMoreHint: "يتم عرض أول 50 نتيجة. ابحث بالاسم أو البريد أو الهاتف للوصول للمزيد.",
      noMembers: "لم يتم العثور على أعضاء.",
      workoutPlans: "خطط التمرين",
      dietPlans: "خطط التغذية",
      attendance: "الحضور الأخير",
      biometrics: "تطور القياسات",
      progressHistory: "سجل التمارين",
      workoutFeedback: "ملاحظات التمرين",
      dietFeedback: "ملاحظات التغذية",
      gymFeedback: "ملاحظات النادي",
      assignWorkout: "إسناد تمرين",
      assignDiet: "إسناد تغذية",
      pickWorkout: "اختر خطة تمرين لإسنادها.",
      pickDiet: "اختر خطة تغذية لإسنادها.",
      pickMember: "اختر عضوًا لعرض التفاصيل.",
      feedback: "الملاحظات",
      noAssignablePlans: "لا توجد خطط تمرين قابلة للإسناد.",
      noAssignableDiets: "لا توجد خطط تغذية قابلة للإسناد.",
      showMore: "أخرى",
      showLess: "عرض أقل",
      openChat: "مراسلة العضو",
      checkInMember: "تسجيل دخول العضو",
      openSupport: "فتح الدعم",
      viewFeedbackQueue: "فتح قائمة الملاحظات",
      quickRegister: "تسجيل سريع",
      quickRegisterSubtitle: "أنشئ حساب عميل من الهاتف. إعداد الاشتراك يبقى منفصلًا.",
      newMember: "عضو جديد",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      phoneNumber: "رقم الهاتف",
      temporaryPassword: "كلمة مرور مؤقتة",
      createMember: "إنشاء عضو",
    },
    financeScreen: {
      title: "نقطة البيع",
      subtitle: "المنتجات والدفع وآخر عمليات البيع.",
      todaySales: "مبيعات اليوم",
      lowStock: "مخزون منخفض",
      products: "المنتجات",
      noProducts: "لا توجد منتجات.",
      sell: "بيع قطعة واحدة",
      recentTransactions: "المعاملات الأخيرة",
      memberId: "معرّف العضو (اختياري)",
    },
    operationsScreen: {
      title: "العمليات",
      subtitle: "المعاملات والإجازات وإجراءات الموظف السريعة.",
      recentTransactions: "المعاملات الأخيرة",
      noTransactions: "لا توجد معاملات حديثة.",
      myLeaves: "إجازاتي",
      noLeaves: "لا توجد طلبات إجازة بعد.",
      openProfile: "فتح الملف الشخصي",
      openLostFound: "فتح المفقودات",
    },
    billingScreen: {
      subtitle: "طلبات التجديد والعروض والإيصالات وسياسة الدفع.",
      renewalRequests: "طلبات التجديد",
      noRenewalRequests: "لا توجد طلبات تجديد بعد.",
      renewalOffers: "عروض التجديد",
      receipts: "الإيصالات",
      paymentPolicy: "سياسة الدفع",
      currentPlan: "الخطة الحالية",
      expiryDate: "تاريخ الانتهاء",
      subscriptionRequests: "طلبات الاشتراك",
      requestRenewal: "طلب تجديد",
      requestFreeze: "طلب تجميد",
      requestUnfreeze: "طلب إلغاء التجميد",
      contactSupport: "التواصل مع الدعم",
      requestExtension: "طلب تمديد",
      requestActivationExtend: "طلب تفعيل / تمديد",
      noExpirySet: "لا يوجد تاريخ انتهاء محدد",
      activeTitle: "الاشتراك نشط",
      activeDesc: "خطتك نشطة. يمكنك طلب تمديد أو تجميد من هذه الصفحة.",
      frozenTitle: "الاشتراك مجمّد",
      frozenDesc: "اشتراكك مجمّد حاليًا. اطلب إلغاء التجميد لاستعادة الوصول الكامل.",
      expiredTitle: "الاشتراك منتهي",
      expiredDesc: "انتهت صلاحية الاشتراك. اطلب التجديد أو التمديد للمتابعة.",
      noneTitle: "لا يوجد اشتراك نشط",
      noneDesc: "لا يوجد اشتراك نشط مرتبط بحسابك. اطلب التفعيل أو التمديد.",
      requestTitle: "إرسال طلب تجديد",
      requestHelp: "أرسل طلب التجديد هنا، ثم ادفع نقداً في النادي وانتظر موافقة الموظفين.",
      selectedOffer: "العرض المختار",
      customerNote: "ملاحظة العميل",
      customerNotePlaceholder: "أخبر النادي متى ستدفع أو اترك ملاحظة مفيدة.",
      submitRequest: "إرسال طلب التجديد",
      submittingRequest: "جارٍ إرسال الطلب...",
    },
    notificationsScreen: {
      subtitle: "آخر أحداث العميل وعناصر صندوق الإشعارات.",
    },
    supportScreen: {
      subtitle: "تذاكر دعم العميل والردود الأخيرة.",
      noTickets: "لا توجد تذاكر دعم بعد.",
      newTicket: "إنشاء تذكرة دعم",
      subject: "الموضوع",
      subjectPlaceholder: "عنوان مختصر للمشكلة",
      messagePlaceholder: "اشرح ما الذي تحتاج إليه",
      sendReply: "إرسال الرد",
      sendingReply: "جارٍ إرسال الرد...",
      creatingTicket: "جارٍ إنشاء التذكرة...",
      pickTicket: "اختر تذكرة لمتابعة المحادثة.",
    },
    chatScreen: {
      subtitle: "محادثات المدرب وعدد الرسائل غير المقروءة.",
      subtitleStart: "اختر مدرباً، وابدأ المحادثة، واحتفظ بالردود في مكان واحد.",
      noThreads: "لا توجد محادثات بعد.",
      startThread: "بدء محادثة",
      newConversation: "محادثة جديدة",
      startConversation: "ابدأ المحادثة",
      selectedContactLabel: "جهة الاتصال المحددة:",
      selectedCoachLabel: "المدرب المحدد:",
      searchContactsPlaceholder: "ابحث بالاسم أو البريد",
      contactPickerPlaceholder: "اختر جهة اتصال",
      searchThreadsPlaceholder: "ابحث في المحادثات",
      threadPickerPlaceholder: "اختر محادثة",
      coachId: "المدرب",
      coachIdPlaceholder: "اختر مدرباً",
      openThread: "فتح المحادثة",
      threadMessages: "رسائل المحادثة",
      threadHint: "عرض محادثة مناسب للهاتف",
      emptyState: "اختر محادثة أو ابدأ محادثة جديدة.",
      messagePlaceholder: "اكتب رسالة",
      markRead: "تعيين كمقروء",
      creatingThread: "جارٍ بدء المحادثة...",
      sendingMessage: "جارٍ إرسال الرسالة...",
      pickThread: "اختر محادثة لعرضها كاملة.",
      noCoaches: "لا يوجد مدربون متاحون بعد.",
      noMatchingContacts: "لا توجد نتائج مطابقة.",
      noMatchingThreads: "لا توجد محادثات مطابقة.",
      threadStarted: "المحادثة جاهزة.",
      unreadActive: "غير مقروء",
      liveNow: "مباشر",
      recording: "جارٍ تسجيل رسالة صوتية...",
      voicePreview: "معاينة الرسالة الصوتية",
      acceptSend: "قبول وإرسال",
      discard: "تجاهل",
      microphoneUnavailable: "تعذر الوصول إلى الميكروفون.",
      voiceUnavailable: "الرسائل الصوتية تحتاج Expo Go أحدث أو نسخة تطوير.",
      voicePlaybackUnavailable: "تشغيل الرسائل الصوتية غير متاح في هذه البيئة.",
    },
    lostFoundScreen: {
      subtitle: "الأغراض التي أبلغت عنها وآخر تحديثات الحالة.",
      noItems: "لا توجد عناصر مفقودات بعد.",
      createItem: "الإبلاغ عن غرض",
      title: "العنوان",
      description: "الوصف",
      category: "الفئة",
      lostCategory: "مفقود",
      foundCategory: "معثور عليه",
      foundLocation: "مكان العثور",
      contactNote: "ملاحظة التواصل",
      commentPlaceholder: "أضف تعليقاً",
      createItemBusy: "جارٍ الإبلاغ عن الغرض...",
      commentBusy: "جارٍ إرسال التعليق...",
      itemComments: "التعليقات",
      addComment: "إضافة تعليق",
      media: "الوسائط",
      photos: "الصور",
      addPhotos: "إضافة صور",
      addPhotosToReport: "أضف صورًا للبلاغ",
      uploadingPhotos: "جارٍ رفع الصور...",
      noPhotos: "لا توجد صور بعد.",
      photoHint: "أضف صورًا واضحة ليسهل على الاستقبال التعرف على الغرض.",
      unsupportedPhoto: "صيغة الصورة غير مدعومة. استخدم JPEG أو PNG أو WebP أو HEIC أو HEIF.",
    },
    profileScreen: {
      subtitle: "بيانات الملف الشخصي وتفضيلات الإشعارات.",
      noPhone: "لا يوجد رقم هاتف بعد",
      noBio: "لا توجد نبذة بعد",
      notificationSettings: "إعدادات الإشعارات",
      push: "الدفع",
      chat: "المحادثة",
      support: "الدعم",
      billing: "الفوترة",
      fullName: "الاسم الكامل",
      phone: "رقم الهاتف",
      bio: "نبذة",
      profilePhoto: "الصورة الشخصية",
      changePhoto: "تغيير الصورة",
      uploadingPhoto: "جارٍ رفع الصورة...",
      noPhoto: "لا توجد صورة شخصية بعد",
      saveProfile: "حفظ الملف",
      savingProfile: "جارٍ حفظ الملف...",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      changePassword: "تغيير كلمة المرور",
      changingPassword: "جارٍ تغيير كلمة المرور...",
      announcements: "الإعلانات",
    },
    feedbackScreen: {
      subtitle: "ملاحظات التمرين والغذاء والنادي المرسلة من حسابك.",
      workout: "ملاحظات التمرين",
      diet: "ملاحظات الغذاء",
      gym: "ملاحظات النادي",
      noWorkout: "لا توجد ملاحظات تمرين بعد.",
      noDiet: "لا توجد ملاحظات غذاء بعد.",
      noGym: "لا توجد ملاحظات للنادي بعد.",
      dietPlan: "خطة غذاء",
      submitGymFeedback: "إرسال ملاحظات للنادي",
      submittingFeedback: "جارٍ إرسال الملاحظات...",
      feedbackSaved: "تم إرسال الملاحظات.",
      rating: "التقييم",
      commentPlaceholder: "أخبر النادي بما كان جيداً أو ما يحتاج إلى اهتمام.",
      equipment: "المعدات",
      cleanliness: "النظافة",
      staff: "الموظفون",
      classes: "الحصص",
      general: "عام",
      coachSubtitle: "قائمة مراجعة المدرب لملاحظات التمرين والتغذية والنادي.",
      member: "العضو",
      openMember: "فتح العضو",
    },
    leavesScreen: {
      subtitle: "طلبات الإجازة وتنظيم فترات الغياب.",
      myLeaves: "طلباتي",
      noLeaves: "لا توجد طلبات إجازة بعد.",
      requestLeave: "طلب إجازة",
      leaveType: "نوع الإجازة",
      startDate: "تاريخ البداية",
      endDate: "تاريخ النهاية",
      reason: "السبب",
      submitting: "جارٍ إرسال الطلب...",
      submitted: "تم إرسال طلب الإجازة.",
    },
    coachPlans: {
      subtitle: "إنشاء وتعديل ونشر وأرشفة وإسناد خطط المدرب.",
      createWorkout: "إنشاء خطة تمرين",
      createDiet: "إنشاء خطة تغذية",
      workoutName: "اسم خطة التمرين",
      dietName: "اسم خطة التغذية",
      description: "الوصف",
      expectedSessions: "الجلسات المتوقعة / 30 يوم",
      exercisesHint: "كل تمرين في سطر: القسم | التمرين | الجولات | التكرارات",
      dietContentHint: "محتوى التغذية أو ملاحظات الوجبات",
      saveDraft: "حفظ كمسودة",
      saveChanges: "حفظ التعديلات",
      publish: "نشر",
      archive: "أرشفة",
      forkDraft: "إنشاء مسودة",
      clone: "نسخ",
      addExercise: "إضافة تمرين",
      addDay: "إضافة يوم",
      addMeal: "إضافة وجبة",
      sectionName: "القسم",
      exerciseName: "التمرين",
      sets: "الجولات",
      reps: "التكرارات",
      dayName: "اليوم",
      mealName: "الوجبة",
      mealItems: "مكونات الوجبة",
      instructions: "التعليمات",
      coachNotes: "ملاحظات المدرب",
      assignedTo: "مسند إلى",
      template: "قالب",
      noWorkoutPlans: "لا توجد خطط تمرين للمدرب بعد.",
      noDietPlans: "لا توجد خطط تغذية للمدرب بعد.",
      editing: "يتم التعديل",
    },
    session: {
      title: "جارٍ تشغيل التطبيق",
      subtitle: "يتم استرجاع الجلسة والتحقق من الوصول للنادي.",
      loading: "جاري تحميل حالة الجلسة الآمنة...",
    },
  },
} as const;

type PreferencesContextValue = {
  locale: Locale;
  themeMode: ThemeMode;
  direction: "ltr" | "rtl";
  isRTL: boolean;
  theme: ThemeTokens;
  fontSet: {
    display: string;
    body: string;
    mono: string;
  };
  copy: CopySet;
  toggleLocale: () => Promise<void>;
  toggleThemeMode: () => Promise<void>;
};

const PreferencesContext = createContext<PreferencesContextValue | null>(null);

export function PreferencesProvider({ children }: PropsWithChildren) {
  const [locale, setLocale] = useState<Locale>("en");
  const [themeMode, setThemeMode] = useState<ThemeMode>("light");

  useEffect(() => {
    let alive = true;
    async function restore() {
      const storedLocale = await SecureStore.getItemAsync(LOCALE_STORAGE_KEY);
      const storedTheme = await SecureStore.getItemAsync(THEME_STORAGE_KEY);
      if (!alive) {
        return;
      }
      if (storedLocale === "en" || storedLocale === "ar") {
        setLocale(storedLocale);
      }
      if (storedTheme === "light" || storedTheme === "dark") {
        setThemeMode(storedTheme);
      }
    }
    void restore();
    return () => {
      alive = false;
    };
  }, []);

  async function toggleLocale() {
    const next = locale === "en" ? "ar" : "en";
    setLocale(next);
    await SecureStore.setItemAsync(LOCALE_STORAGE_KEY, next);
  }

  async function toggleThemeMode() {
    const next = themeMode === "light" ? "dark" : "light";
    setThemeMode(next);
    await SecureStore.setItemAsync(THEME_STORAGE_KEY, next);
  }

  const value = useMemo<PreferencesContextValue>(() => {
    const direction = locale === "ar" ? "rtl" : "ltr";
    return {
      locale,
      themeMode,
      direction,
      isRTL: direction === "rtl",
      theme: themes[themeMode],
      fontSet: fonts[locale] as { display: string; body: string; mono: string },
      copy: copy[locale],
      toggleLocale,
      toggleThemeMode,
    };
  }, [locale, themeMode]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error("usePreferences must be used within PreferencesProvider");
  }
  return context;
}
